### ISSUE TITLE
good to have express app variables

### ISSUE THREAD

**Issue by sureshvarman-cronj** [OpusCapita/web-init#6]

**Comment by kwierchris** [comment]
What exactly do we need?

**Comment by sureshvarman-cronj** [comment]
I need to setup viewengine to `ejs`, and also we might need this to setup some application secret, which we can access on any routes. I have already added that, will push along with auth service, testing auth service

**Comment by kwierchris** [comment]
So looks like this is nothing we can fix by using the current middleware configuration system. Could you give me an example please because I have currently no idea how this should look.

**Comment by sureshvarman-cronj** [comment]
app.set(variable, value);
In my case i need to set `view engine`.

But we might need for different variables also, like appSecret, cookie secrets, etc,...

**Comment by kwierchris** [comment]
understood thx.
