### ISSUE TITLE
need option to disable User identitymiddleware.

### ISSUE THREAD

**Issue by sureshvarman-cronj** [OpusCapita/web-init#7]

**Comment by kwierchris** [comment]
Any proposals as this is hardcoded.

**Comment by sureshvarman-cronj** [comment]
I have made changes with option to `disableIdentity` default to false, we can disable the identity middleware using `true`, Will push this also along with auth, since testing with auth service.

**Comment by kwierchris** [comment]
If possible, please do not use negative terms. It should not be **disableIdentity** to **false** but **enableIdentity** to **true** :)

**Comment by sureshvarman-cronj** [comment]
ah, okay
